In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Python/Pandas/Paitent_Project/patient_master_1.csv")

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/Python/Pandas/Paitent_Project/patient_master_2.csv")

In [ ]:
df1.shape

(20000, 25)

In [ ]:
df = pd.concat([df1,df2])

In [ ]:
df.shape

(160000, 25)

In [ ]:
#1.	Load the patient master CSV file into a Pandas DataFrame

#2.	Display the first 5 rows of the dataset
df.head()

#3.	Display the last 5 rows of the dataset
df.tail()

#4.	Find the total number of rows and columns
df.shape

#5.	Display column names
df.columns

#6.	Display data types of all columns
df.dtypes

#7.	Show summary statistics for numerical columns
df.describe()

#8.	Show summary statistics for all columns
df.describe(include = "all")

#9.	Check how many missing values exist per column
df.isna().sum()

#10.	Check if the dataset contains duplicate Patient_IDs
df.duplicated().sum()

#11.	Find the total number of unique patients
df["Patient_ID"].nunique()

#12.	Display memory usage of the DataFrame
df.memory_usage()

#13.	Sort patients by Age in descending order
df.sort_values("Age", ascending = False)

#14.	Sort patients by Registration_Date in ascending order
df.sort_values("Registration_Date")

#15.	Display random 10 patient records
df.sample(4)
df.head(6)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Age_Group,age_group
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19,Adult,Adult
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12,Adult,Adult
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25,Adult,Adult
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17,Adult,Adult
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04,Adult,Adult
5,P00006,Suresh,Kulkarni,Male,46,1979-09-03,A+,Married,9469747118,user6@mail.com,...,32.4,No,Occasionally,NaN,D110,ICICI Lombard,POL589437,2022-01-24,Adult,Adult

In [ ]:
#🔹 SECTION 2: FILTERING & CONDITIONAL SELECTION (16–35)
#16.	Find all male patients
df[df["Gender"] == "Male"]



#17.	Find all female patients above 50 years
df[(df["Gender"] == "Female") & (df["Age"] > 50)]

#18.	Find patients from Pune city
df[df["City"] == "Pune"]

#19.	Find patients suffering from Diabetes
df[df["Chronic_Condition"] == "Diabetes"]

#20.	Find patients who are smokers
df[df["Smoker"] == "Yes"]

#21.	Find patients who consume alcohol occasionally
df[df["Alcohol_Consumption"] == "Sometimes"]

#22.	Find patients with BMI greater than 30
df[df["BMI"] > 30]

#23.	Find patients with no chronic condition
df[df["Chronic_Condition"] == "None"]

#24.	Find patients registered after 2023
df[df["Registration_Date"] > "2023-01-01"]

#25.	Find patients with blood group O+
df[df["Blood_Group"] == "O+"]

#26.	Find patients insured under Star Health
df[df["Insurance_Plan"] == "Star Health"]

#27.	Find patients whose height is above 175 cm
df[df["Height"] > 175]

#28.	Find patients aged between 30 and 45
df[(df["Age"] > 30) & (df["Age"] < 45)]

#29.	Find patients from Mumbai OR Pune
df[(df["City"] == "Mumbai") | (df["City"] == "Pune")]

#30.	Find patients who are married and diabetic
df[(df["Marital_Status"] == "Married") & (df["Chronic_Condition"] == "Diabetes")]

#31.	Find patients whose email contains “gmail”
df[df["Email"].str.contains("gmail")]

#32.	Find patients whose Patient_ID starts with “P1”
df[df["Patient_ID"].str.startswith("P1")]

#33.	Find patients with weight above average weight
df[df["Weight"] > df["Weight"].mean()]

#34.	Find patients having Asthma or Thyroid
df[(df['Chronic_Condition'] == 'Asthma') | (df['Chronic_Condition'] == 'Thyroid')]

#35.	Find patients whose BMI is below 18.5
df[df["BMI"] < 18.5]

#36 Remove age-gruop column
#df.drop(columns = "age_group", inplace = True)

# Usages if loc and iloc function
df.loc[4,['Last_Name', "Age"]]

  Last_Name  Age
4     Verma   41
4  Kulkarni   59

In [ ]:
#56.	Create a new column Age_Group (Young, Adult, Senior)

df["Age_Group"] = df["Age"].apply(lambda i :  "Senior" if i  > 60 else ("Adult" if i > 18 else "Young"))

In [ ]:
#73.	Sort patients by BMI descending
df.head(2)

df.sort_values("BMI", ascending  = False)

#74.	Reset index after sorting
df.reset_index(drop = True)

#76.	Find top 5 cities with highest average BMI
df.groupby("City")["BMI"].mean().sort_values(ascending= False).head()

City
Nagpur      25.927700
Mumbai      25.883366
Pune        25.837583
Nashik      25.835835
Kolhapur    25.786412
Name: BMI, dtype: float64